project_name: f2

before:
  hooks:
    - go mod download
builds:
  - id: binary_archives
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - android
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: android
        goarch: 386
      - goos: windows
        goarch: arm64
    main: ./cmd/f2

archives:
  - files:
      - LICENCE
      - README.md
      - CHANGELOG.md
      - scripts/completions/*
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: main_packages
    vendor: '{{ .Env.REPO_OWNER }}'
    homepage: '{{ .Env.REPO_WEBSITE }}'
    maintainer: '{{ .Env.REPO_MAINTAINER }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    license: MIT
    formats:
      - deb
      - rpm
    recommends:
      - exiftool
    contents:
      - src: scripts/completions/f2.bash
        dst: /usr/share/bash-completion/completions/f2
        file_info:
          mode: 0644
      - src: scripts/completions/f2.fish
        dst: /usr/share/fish/vendor_completions.d/f2.fish
        file_info:
          mode: 0644
      - src: scripts/completions/f2.zsh
        dst: /usr/share/zsh/vendor-completions/_f2
        file_info:
          mode: 0644

  - id: other_packages
    vendor: '{{ .Env.REPO_OWNER }}'
    homepage: '{{ .Env.REPO_WEBSITE }}'
    maintainer: '{{ .Env.REPO_MAINTAINER }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    license: MIT
    formats:
      - apk
      - termux.deb
      - archlinux
    recommends:
      - exiftool
    contents:
      - src: scripts/completions/f2.bash
        dst: /usr/share/bash-completion/completions/f2
        file_info:
          mode: 0644
      - src: scripts/completions/f2.fish
        dst: /usr/share/fish/vendor_completions.d/f2.fish
        file_info:
          mode: 0644
      - src: scripts/completions/f2.zsh
        dst: /usr/share/zsh/vendor-completions/_f2
        file_info:
          mode: 0644

publishers:
  - name: fury.io
    ids:
      - main_packages
    dir: '{{ dir .ArtifactPath }}'
    cmd:
      curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_PUSH_TOKEN
      }}@push.fury.io/{{ .Env.FURY_USERNAME }}/

winget:
  - publisher: '{{ .Env.REPO_OWNER }}'
    license: MIT
    copyright: '{{ .Env.REPO_AUTHOR_NAME }}'
    homepage: '{{ .Env.REPO_WEBSITE }}'
    short_description: '{{ .Env.REPO_DESCRIPTION }}'
    repository:
      owner: '{{ .Env.REPO_OWNER }}'
      token: '{{ .Env.GORELEASER_GITHUB_TOKEN }}'
      name: winget-pkgs
      branch: '{{.ProjectName}}-{{.Version}}'
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

scoops:
  - url_template:
      'https://github.com/ayoisaiah/f2/releases/download/{{ .Tag }}/{{
      .ArtifactName }}'
    repository:
      owner: '{{ .Env.REPO_OWNER }}'
      name: scoop-bucket
      token: '{{ .Env.GORELEASER_GITHUB_TOKEN }}'
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: '{{ .Env.REPO_WEBSITE }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    license: MIT

brews:
  - repository:
      owner: '{{ .Env.REPO_OWNER }}'
      name: homebrew-tap
      token: '{{ .Env.GORELEASER_GITHUB_TOKEN }}'
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: '{{ .Env.REPO_WEBSITE }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    install: |-
      bin.install "{{ with .Env.REPO_BINARY_NAME }}{{ . }}{{ else }}{{ .ProjectName }}{{ end }}"
    dependencies:
      - name: exiftool
        type: optional
