repos:
  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-fmt
        name: format code
        entry: just fmt
        language: system
        files: \.go$
        pass_filenames: false

      - id: golangci-lint
        name: lint code
        entry: just lint
        language: system
        files: \.go$
        pass_filenames: false

      - id: govulncheck
        name: vulnerability check
        entry: just vulncheck
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-test
        name: run tests
        entry: just test
        language: system
        files: \.go$
        pass_filenames: false
